# Generated by Django 2.2.2 on 2019-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190621_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_nutrition',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
